### ISSUE TITLE
Form feedback styles out of date

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/service-manual-frontend#115]
The styles for the form fields look out of date - are we using an older version of GOV.UK Template?. When inputs get focus, they lose their border. This bug was fixed in alphagov/govuk_template#259

Service manual input:
![screen shot 2017-04-10 at 17 14 01](https://cloud.githubusercontent.com/assets/2204224/24871354/4039f9b0-1e11-11e7-8eec-4555d9130442.png)

GOV.UK Elements input:
![screen shot 2017-04-10 at 17 14 21](https://cloud.githubusercontent.com/assets/2204224/24871358/43546162-1e11-11e7-815e-cadbd8840a9c.png)

**Comment by gemmaleigh** [comment]
I think this might need to be filed over on static - as it isn't using version [0.19.1 of govuk_template](https://github.com/alphagov/govuk_template/pull/262).

**Comment by edwardhorsford** [comment]
Thanks Gemma!

Shall I close this issue? Static automatically pushes to us, right?

**Comment by 36degrees** [comment]
I believe this has been resolved.
