### ISSUE TITLE
There should be one h1 per page, but one is in header, one in content

### ISSUE THREAD

**Issue by selfthinker** [alphagov/service-manual-frontend#125]
Every page in the Service Manual has two h1s (if the content starts with an h1, which it probably always does), because the header includes an h1 (saying "Service Manual").
This should be adjusted to be as in [govuk_template](https://github.com/alphagov/govuk_template/blob/master/source/views/layouts/govuk_template.html.erb#L62). Otherwise it's inconsistent with the rest of gov.uk and screen reader users could get confused.

**Comment by chrismoorembe** [comment]
As a screen reader user, I need to be able to jump to the first H1 on a page, as typically this is where the main content starts. If you place additional H1s prior to the main content, I then have to take additional steps until I finally reach the main content area.

In later versions of JAWS, it is possible to jump directly to the main content area by using a keyboard shortcut, but by default I'm a VoiceOver user.

Please make GOV.UK consistent by only having one H1 and ensuring it is at the start of the main content and below any banners or breadcrumbs.

**Comment by 36degrees** [comment]
This was resolved in #240
