### ISSUE TITLE
Phase banner says content is new when it isn't

### ISSUE THREAD

**Issue by benjamin-mortimer** [alphagov/service-manual-frontend#209]
On "guides", the beta phase banner says "This is new guidance. Complete our quick 5-question survey to help us improve it."

A lot of the guidance isn't new - it's been around for over a year in some cases. The age of the guidance is shown to users under the guide's top heading so the contrast is rather jarring.

For example: https://www.gov.uk/service-manual/design/naming-your-service:

![screen shot 2018-05-17 at 12 36 38](https://user-images.githubusercontent.com/21359750/40175111-09877596-59cf-11e8-9775-f0ab7ae9cef3.png)

I had a go at changing this in a pull-request, since (I think) it's just an erb file and a test: https://github.com/alphagov/service-manual-frontend/pull/208

**Comment by 36degrees** [comment]
This was resolved in #208
