### ISSUE TITLE
Scaled screenshots in the manual look blurry.

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/service-manual-frontend#80]
We've updated some images in the manual - I provided retina screenshots, but when scaled down they look blurry.

I believe [setting the image `rendering-property`](https://css-tricks.com/almanac/properties/i/image-rendering/) may improve the appearance.

Before:
![screen shot 2016-12-08 at 10 08 47](https://cloud.githubusercontent.com/assets/2204224/21005838/5dca9c62-bd2e-11e6-8e12-6803770b1136.png)

After:
![screen shot 2016-12-08 at 10 08 31](https://cloud.githubusercontent.com/assets/2204224/21005844/627a9c8a-bd2e-11e6-8413-588ae1dcccdb.png)

The improvement is significant on Chrome on a non-retina screen. I don't know what it looks like on other browsers and devices.

**Comment by AgaDufrat** [comment]
Closing the issue as it's now 7+ years old and this repo is being archived.
