### ISSUE TITLE
Sticky nav jumps when scrolling down

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/service-manual-frontend#81]
The sticky nav scrolls briefly to the top of the page before jumping in to place. Ideally it would never go above where the sticky position is.

Video:
![service-manual-sticky-bug](https://cloud.githubusercontent.com/assets/2204224/21011572/d3db2938-bd49-11e6-9068-e7d23ac782d8.gif)

Seen on Chrome 54 on OSx El Capitan 10.11.6

**Comment by nickcolley** [comment]
I'd propose we use `position: sticky` and have this an enhancement, if we determine this is core functionality then polyfill `position: sticky` as needed.

**Comment by 36degrees** [comment]
This has been fixed.
